#pragma once

#define NVIDIA_API_INIT_SUCCESS 0
#define NVIDIA_API_INIT_FAILED -1
#define NVIDIA_API_ALREADY_INITIALIZED -2
#define NVIDIA_API_NOT_INITIALIZED -3
#define NO_GPU_FOUND -4
#define NVIDIA_API_GET_THERMAL_SETTINGS_FAILED -5;
#define NO_THERMAL_SENSORS_FOUND -6;

